site_name: SPFx-uifabric-themes
nav:
  - Home: 'index.md'
  - Release notes: 'release-notes.md'
  - License: 'license.md'
  - SASS:
    - How To: ./sass/how-to.md
    - SASS Variable reference: ./sass/uif.theme.md
    - Typography: ./sass/typography.md
    - State Styles: ./sass/statestyles.md
  - CSS: 'css-variables.md'
  - TypeScript: 'typescript.md'
theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'pink'
markdown_extensions:
  - codehilite
  - admonition